blank_issues_enabled: false
contact_links:
    about: Ask questions and discuss with other yonode users in real time.
  - name: Questions & Discussions
    url: https://github.com/sharafdin/yonode/discussions
    about: Use GitHub discussions for message-board style questions and discussions.