name: "Documentation Improvement"
description: "Propose enhancements or new content for Yonode documentation"
labels:
  - "documentation"
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for helping improve Yonode's documentation!** 

        Before submitting, please check if a similar suggestion exists.

  - type: checkboxes
    id: documentation_needs
    attributes:
      label: "What issues do you find with the current documentation?"
      options:
        - label: "Incomplete (missing information)"
        - label: "Hard to understand (unclear explanations)"
        - label: "Incorrect (inaccurate information)"
        - label: "Lacking examples"
        - label: "Outdated (not up-to-date)"
        - label: "Other (please specify)"

  - type: textarea
    id: problem_description
    attributes:
      label: "Describe the problem"
      description: "What specific information or clarity is lacking in the documentation?"
      placeholder: "I couldn't find info on ..., because ..."
    validations:
      required: true

  - type: textarea
    id: proposed_improvements
    attributes:
      label: "Proposed changes"
      description: "How do you suggest we improve the documentation? Please provide your recommendations or ideas."
      placeholder: "To improve ..., I suggest ..."
    validations:
      required: true

  - type: textarea
    id: why_important
    attributes:
      label: "Why it matters"
      description: "Explain why these changes are important. How will they benefit Yonode users or the community?"
      placeholder: "Improving this is important because ..."
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: "Before submitting, please make sure you:"
      options:
        - label: "Searched for similar requests."
        - label: "Clearly described the problem and your proposed solution."
        - label: "Explained the benefit of the improvement."
