name: "New Feature Proposal"
description: Suggest an enhancement for Yonode
labels: ["type: feature request", "status: review pending"]
body:
  - type: markdown
    attributes:
      value: |
        **We're thrilled you're looking to help improve Yonode!**

        Your contributions and ideas are vital to making sure Yonode stays innovative and responsive to community needs. Before you begin, kindly ensure no similar feature request has been submitted by [searching existing issues](https://github.com/sharafdin/yonode/issues).
        
        Let's create something amazing together!

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: "What is the essence of the feature you're proposing? Summarize your proposal in a few sentences, highlighting the problem it solves or the value it adds to Yonode."
      placeholder: "Summarize the feature succinctly, e.g., 'Implementing X feature to enhance Y capability.'"
    validations:
      required: true

  - type: textarea
    id: detailed-solution
    attributes:
      label: Detailed Solution
      description: "Provide a detailed description of your proposed solution. Include how it should work in various contexts within Yonode, if applicable."
      placeholder: "Detail your solution, including any technical specifics and how it integrates with existing functionalities."
    validations:
      required: true

  - type: textarea
    id: motivation-and-goals
    attributes:
      label: Motivation and Goals
      description: "Explain the motivation behind this feature request. What goals are you trying to achieve? How does it benefit Yonode and its users?"
      placeholder: "Describe why this feature is necessary and the benefits it will bring."

  - type: textarea
    id: alternatives-and-considerations
    attributes:
      label: Alternatives and Considerations
      description: "Have you considered any alternative solutions or features? Why are they less preferable?"
      placeholder: "Explain any alternatives you've considered and why your proposed solution is better."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Feel free to provide any additional context or screenshots that could help us understand your feature request better."
      placeholder: "Any other information, context, or screenshots."

  - type: checkboxes
    id: compliance-checklist
    attributes:
      label: Compliance Checklist
      description: "Ensure you've completed the following steps before submitting your feature request:"
      options:
        - label: I have checked for similar feature requests and found none.
        - label: I have explained the feature with enough detail for it to be understood.
        - label: I have provided a clear rationale for why this feature should be implemented.
