name: Publish Yonode Package

on:
  push:
    branches:
      - yonode

jobs:
  publish:
    name: Publish Yonode Package
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
