name: Publish Yonode Package

on:
  push:
    branches:
      - main

jobs:
  publish:
   # prevents this action from running on forks
    if: github.repository == 'sharafdin/yonode'
    name: Publish Yonode Package
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org/'
      - name: Publish to npm
        run: npm publish --access public
        working-directory: packages/yonode
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
